name: SAST SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  devsecops-sonar:
    runs-on: ubuntu-latest

    steps:
            - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://sonarqube-sonarqube.sonarqube:9000
          SONAR_PROJECT_KEY: app
        run: |
          docker run \
            --network host \
            --platform linux/amd64 \
            --rm \
            -e SONAR_HOST_URL="${SONAR_HOST_URL}" \
            -e SONAR_TOKEN="${SONAR_TOKEN}" \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli \
              -Dsonar.projectKey=app \
              -Dsonar.projectName="DevSecOps App" \
              -Dsonar.sources=${SONAR_PROJECT_KEY}

      - name: Check Quality Gate
        id: quality-gate
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://sonarqube-sonarqube.sonarqube:9000
          SONAR_PROJECT_KEY: app
        run: |
          sleep 10
          STATUS=$(curl -s -u ${SONAR_TOKEN}: -G \
            --data-urlencode "projectKey=${SONAR_PROJECT_KEY}" \
            "${SONAR_HOST_URL}/api/qualitygates/project_status" \
            | jq -r '.projectStatus.status')

          if [ "${STATUS}" != "OK" ]; then
            echo "❌ Quality Gate failed with status: ${STATUS}"
            exit 1
          else
            echo "✅ Quality Gate passed"
          fi