name: SAST SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  devsecops-sonar:
    runs-on: ubuntu-latest

    steps:
      #Checkout do código-fonte
      - name: Checkout do código
        uses: actions/checkout@v4

      #Configuração do Python
      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"      
      
      #Rodar análise com SonarCloud
      - name: Rodar análise SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "➡️ Iniciando análise de código com SonarCloud..."
          sonar-scanner \
            -Dsonar.projectKey=CESAR-DevSecOps_pygoat \
            -Dsonar.organization=DevSecOps \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.version=3.10 \
            -Dsonar.sources=. \
            -Dsonar.tests=tests \
            -Dsonar.test.inclusions="**/tests/**" \
            -Dsonar.exclusions="**/migrations/**,**/venv/**" \
            -Dsonar.sourceEncoding=UTF-8
          echo "✅ Análise concluída! Confira os resultados no painel do SonarCloud."

      #Verificação de dependências com Safety
      - name: 🧾 Rodar Safety - Dependências vulneráveis
        run: |
          pip install safety
          safety check --full-report || true